---
title: "The Fast and the Furious: Tracking the Effect of the Tomoa Skip on Speed Climbing"
output: ioslides_presentation
date: "2023-06-09"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Best Times Per Event
```{r message=FALSE, warning=FALSE}

library(ggplot2)
library(dplyr)
library(tidyr)

load("../../data/mTimes_skip.Rdata")
load("../../data/wTimes_skip.Rdata")

m_times_update |>
  bind_rows(w_times_update) |>
  pivot_longer(cols = c("best_qual", "final", "lane_a", "lane_b", "first_round", "quarter", "semi", "small_final", "big_final"), names_to = "round", values_to = "time") |>
  group_by(fname, lname, tomoa_skip, sex, event_id, year, start_date) |>
  # Handle case where all values in best_time are NA 
  summarise(best_time = if (all(is.na(time))) NA else min(time, na.rm = TRUE)) |>
  filter(!is.na(best_time)) |>
  ggplot() +
  geom_jitter(aes(start_date, best_time, color = tomoa_skip)) +
  facet_wrap(.~sex)
```

## All Qualifier Times: Mens and Womens 

``` {r message = FALSE, warning = FALSE}
m_times_update |>
  bind_rows(w_times_update) |>
  pivot_longer(cols = c("best_qual", "lane_a", "lane_b"), names_to = "round", values_to = "qual_time") |>
  group_by(fname, lname, tomoa_skip, sex, event_id, year, start_date) |>
  #Remove outliers -- OK?
  filter(!is.na(qual_time) & qual_time < 60)  |>
  ggplot() +
  geom_jitter(aes(start_date, qual_time, color = tomoa_skip)) + 
  facet_wrap(.~sex) + 
  ggtitle("Qualifying Times for Men and Women")
```

## All Final Times: Mens and Womens

``` {r message = FALSE, warning = FALSE}
m_times_update |>
  bind_rows(w_times_update) |>
  pivot_longer(cols = c("final", "first_round", "quarter", "semi", "small_final", "big_final"), names_to = "round", values_to = "final_time") |>
  group_by(fname, lname, sex, tomoa_skip, event_id, year, start_date) |>
  # There are 3 outliers ~100
  filter(!is.na(final_time) & final_time < 95)  |>
  ggplot() +
  geom_jitter(aes(start_date, final_time, color = tomoa_skip)) + 
  facet_wrap(.~sex)

```



